# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: '078f1e6f-c437-441a-ace5-4af6ab33087e'
    pipeline: '2'
    buildVersionToDownload: 'latest'
    downloadType: 'single'
    artifactName: '*'
    itemPattern: '*'
    downloadPath: 'D:\SebG Enterprizes HQ\Project - Web API Tutorial 2\Artifacts'
    checkDownloadedFiles: true
    extractTars: true